#!/bin/bash

# 1. Generate SSH Key
echo "Generating SSH key..."
ssh-keygen -t rsa -m PEM -f ~/.ssh/docker-agent -N "" <<< y >/dev/null 2>&1

# 2. Output the private key
echo "Private Key:"
cat ~/.ssh/docker-agent

# 3. Build the Docker image
echo "Building Docker image..."
docker build -t docker-agent-debian .

# 4. Run the Docker container with the public key
PUBLIC_KEY=$(cat ~/.ssh/docker-agent.pub)

echo "Running Docker container with the public key..."
docker run -td --privileged -p 7777:22 --name docker-agent -e "JENKINS_AGENT_SSH_PUBKEY=${PUBLIC_KEY}" docker-agent-debian

echo "Jnekins Docker agent started."